#!/bin/sh
module="vspi_drv"
device="vspi_drv"
#mode="664" // should be changed back to 664
mode="777"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^users:' /etc/group; then
    group="users"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk -v MODULE=$module '$2==MODULE {print $1;}' /proc/devices)

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}[0-1]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
chgrp $group /dev/${device}[0-1] 
chmod $mode  /dev/${device}[0-1]
